apiVersion: apps/v1
kind: Deployment
metadata:
  name: shashankcapstone
  labels:
    app: shashankcapstone
spec:
  selector:
    matchLabels:
      app: shashankcapstone
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: shashankcapstone
    spec:
      containers:
      - name: shashankcapstone
        image: shashank81jain/shashankcapstone
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
