apiVersion: v1
kind: Service
metadata:
  name: shashankcapstone
#  namespace: eks-capstone-ns
  labels:
    app: shashankcapstone
spec:
  type: LoadBalancer
  selector:
    app: shashankcapstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
